@startuml
!pragma graphviz_dot jdot
package eu.reverseengineer.apidoc.api {
    interface IApiDocFilter {
        +run(api: IApiDocSubject)
    }
    interface IApiDocSubject {
        +api() : OpenApi
    }
    IApiDocFilter ..> IApiDocSubject
}
@enduml